### ISSUE TITLE
Task: Set up Spinnaker to deploy to EC2

### ISSUE THREAD

**Issue by justinrlee** [armory/minnaker#14]
Configure Spinnaker with an AWS account, including documentation for a repeatable way to set this up, and how to set up a pipeline that bakes and deploys.

**Comment by away168** [comment]
i've added the AWS account.  largely following this doc: 
https://docs.armory.io/spinnaker-install-admin-guides/add-aws-account-iam/

**Comment by away168** [comment]
have a sample pipeline that deploys nginx.

**Comment by away168** [comment]
no additional instructions - other than sample pipeline built.
