### ISSUE TITLE
Minnaker install: initial login redirects to an invalid path

### ISSUE THREAD

**Issue by JeffCertain** [armory/minnaker#27]
First login redirected to incorrect path. 
path: https://10.176.1.242/api/v1/auth/redirect?to=http%3A%2F%2F10.176.1.242%2F%23%2Fsearch

response: {"timestamp":1575481570976,"status":400,"error":"Bad Request","message":"Requested redirect address not recognized."}

Hitting the IP address again gave me access to spinnaker, and subsequent logins work correctly.

**Comment by leefaus** [comment]
Thanks for testing this @JeffCertain .  We will look into this as a bug and determine what could be causing this issue on first login.

**Comment by aleon1220** [comment]
> First login redirected to incorrect path.
> path: https://10.176.1.242/api/v1/auth/redirect?to=http%3A%2F%2F10.176.1.242%2F%23%2Fsearch
> 
> response: {"timestamp":1575481570976,"status":400,"error":"Bad Request","message":"Requested redirect address not recognized."}
> 
> Hitting the IP address again gave me access to spinnaker, and subsequent logins work correctly.

Exactly same issue here.

**Comment by justinrlee** [comment]
you have to access on https, not http
