### ISSUE TITLE
what is the purpose of statefulset=mariadb-0  ? 

### ISSUE THREAD

**Issue by aleon1220** [armory/minnaker#55]
Is it for [Orca SQL](https://www.spinnaker.io/setup/productionize/persistence/orca-sql/#set-up-orca-to-use-sql)??

Is there any docs from minnaker that point to the usage of this stateful set?

thanks so much

![image](https://user-images.githubusercontent.com/2084646/82190084-97184f00-9944-11ea-97d0-6ea9db3abe9a.png)

**Comment by aimeeu** [comment]
Minnaker uses Kubernetes to deploy Spinnaker services. StatefulSet is a Kubernetes object: https://kubernetes.io/docs/concepts/workloads/controllers/statefulset/

I don't actually know what mariadb hooks up to. I'd have to dig through the scripts or ask Justin.

**Comment by aleon1220** [comment]
> Minnaker uses Kubernetes to deploy Spinnaker services. StatefulSet is a Kubernetes object: https://kubernetes.io/docs/concepts/workloads/controllers/statefulset/
> 
> I don't actually know what mariadb hooks up to. I'd have to dig through the scripts or ask Justin.

Just an update on this: 
if you want to persist the pipeline and task execution history you need to set up the mariadb or mysql instance with [orca-sql Spinnaker instructions](https://www.spinnaker.io/setup/productionize/persistence/orca-sql/)

Unfortunately it failed for some reason and the issue and solution are at: 
[5788](https://github.com/spinnaker/spinnaker/issues/5788)

**Comment by justinrlee** [comment]
Oh, the MariaDB stuff is basically building out some skeleton for stuff I'd like to implement in the future.  Haven't got there...

**Comment by aleon1220** [comment]
Thanks @justinrlee I used the mariadb stateful set to get Orca SQL working and persist the pipeline executions. Useful for demos when clients ask too many details and you need to reboot. So that they dont ask "why are the pipeline executions gone now?"

Hey if any of you could give me insight on how to get phpmyAdmin MySQL manager up and running in the K3S cluster that would be great.
thanks
Closing this issue.
